### PR TITLE
Initial RaspiOS Buster support

### PR DESCRIPTION
**Pull request by iluminat23**
This is  intended as starting point for the Buster development.

### CODE REVIEW

**Review by zhan-kunbus — COMMENTED** [review]
libarmmem-v7l.so maybe needed at booting 
# activate settings
+echo /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so > $IMAGEDIR/etc/ld.so.preload
 chroot $IMAGEDIR dpkg-reconfigure -fnoninteractive keyboard-configuration

**Comment by iluminat23** [comment]
I don't think this is needed. The content of the file should be ok and working on the real system. Other wise the image wouldn't work on an rpi either. I just wanted to get this out of the way as long we are using qemu.

**Comment by l1k** [comment]
Re 0e7a737b91ce: Looks wrong, please consider a solution along the lines of 54340de30149.
Re 8d529b83ebf7: Please use separate commits for these two changes.

**Comment by iluminat23** [comment]
Hi @l1k,
thanks for your input. I will look into this when I have time. My priorities shifted recently ...

**Comment by l1k** [comment]
I feel you. ;)

**Pull request merged**
