### PR TITLE
Misc changes for customize_image

### PR DESCRIPTION
**Pull request by xrmx**
Use losetup for finding loop devices, don't assume lightdm is here and also cleanup a test that fails on my shell (dash)

### CODE REVIEW

**Comment by xrmx** [comment]
On top of that i've some changes that make it work with qemu-arm-static which i find quite handy instead of building on an arm device.

**Comment by l1k** [comment]
Commits 	xrmx/imagebakery@fe69e01 and xrmx/imagebakery@fec0bf3 LGTM, I've cherry-picked these two now.

**Comment by l1k** [comment]
Could you post the error you got that necessitated commit xrmx/imagebakery@0158081? It seems to work fine for me (dash Debian package 0.5.7-4). Thanks!

**Comment by xrmx** [comment]
The issue was because the list of packages was not quoted. Here's a reproducer:

```
set -ex

if [ hi there ] ; then
    echo
fi
```
which gives:

```
foo.sh: 3: [: hi: unexpected operator
```

**Comment by xrmx** [comment]
I've updated the pull request:
- fixed debian package installation on chroot
- adding support for creating an image on x86 with qemu-user-static
- make apache2 setup conditional on apache2 currently installed

Feel free to merge or cherry-pick stuff.

**Comment by l1k** [comment]
Sorry for the delay, got sidetracked. :-(

<blockquote> The issue was because the list of packages was not quoted</blockquote>

Ah, good catch. However it seems the simplest solution is to simply add double quotes. I've taken the liberty to modify your commit xrmx/imagebakery@d1499764135fa3931241250e0a9c8cf948c8a82a accordingly and pushed the result as commit 28baf0a1ff3e228b8cc8f9c5c20532dd5dbcfa7b. Hope that's okay with you. Please shout if not. This solution should also obviate the need for commit xrmx/imagebakery@64bb2b9a33b52713ff81c02cad30b0a3daf0ea42.

**Comment by l1k** [comment]
A few dumb questions on the remaining commits in this pull:

Regarding commit xrmx/imagebakery@37c5086240a64f6f4932e7ad1e9f86897a322149: With `dpkg --root`, the files are unpacked from a process outside the chroot, but the preinst/postinst scripts are executed *within* the chroot. The behaviour should thus essentially be the same as with this commit, so I'm not sure why this is needed. What am I missing?

Regarding commit xrmx/imagebakery@ee9f79c5bf556e8ec3dde0450162090f972f883b, apache2 is pulled in by the `revpi-webstatus` package. If you don't have apache2 installed, did you manually remove `revpi-webstatus` from `debs-to-download`?

Regarding commit xrmx/imagebakery@ed9020bd764c0708c47e01ed34ad185003ae4694, my expectation would be that the call to `chroot $IMAGEDIR /etc/init.d/apache2 stop` in `customize_image.sh` should end these processes in an orderly fashion. How can it be that they're still hanging around?

Thanks!

**Comment by xrmx** [comment]
Il 12/06/2017 17:04, l1k ha scritto:
> A few dumb questions on the remaining commits in this pull:
>
> Regarding commit xrmx/imagebakery@37c5086
> <https://github.com/xrmx/imagebakery/commit/37c5086240a64f6f4932e7ad1e9f86897a322149>:
> With |dpkg --root|, the files are unpacked from a process outside the chroot,
> but the preinst/postinst scripts are executed /within/ the chroot. The behaviour
> should thus essentially be the same as with this commit, so I'm not sure why
> this is needed. What am I missing?

I don't have the error at hand but it didn't work

> Regarding commit xrmx/imagebakery@ee9f79c
> <https://github.com/xrmx/imagebakery/commit/ee9f79c5bf556e8ec3dde0450162090f972f883b>,
> apache2 is pulled in by the |revpi-webstatus| package. If you don't have apache2
> installed, did you manually remove |revpi-webstatus| from |debs-to-download|?

Yes, see
https://github.com/xrmx/imagebakery/commit/583402fe50442e339467c32c775a583691b52f29

> Regarding commit xrmx/imagebakery@ed9020b
> <https://github.com/xrmx/imagebakery/commit/ed9020bd764c0708c47e01ed34ad185003ae4694>,
> my expectation would be that the call to |chroot $IMAGEDIR /etc/init.d/apache2
> stop| in |customize_image.sh| should end these processes in an orderly fashion.
> How can it be that they're still hanging around?

Franly speaking I haven't investigated that much as i stopped installing 
apache2, that code is a guard for whatever would block umounting.


-- 
Riccardo Magliocchetti

**Comment by xrmx** [comment]
Il 12/06/2017 16:21, l1k ha scritto:
> Sorry for the delay, got sidetracked. :-(
>
>     The issue was because the list of packages was not quoted
>
> Ah, good catch. However it seems the simplest solution is to simply add double
> quotes. I've taken the liberty to modify your commit xrmx/imagebakery@d149976
> <https://github.com/xrmx/imagebakery/commit/d1499764135fa3931241250e0a9c8cf948c8a82a>
> accordingly and pushed the result as commit 28baf0a
> <https://github.com/RevolutionPi/imagebakery/commit/28baf0a1ff3e228b8cc8f9c5c20532dd5dbcfa7b>.
> Hope that's okay with you. Please shout if not. This solution should also
> obviate the need for commit xrmx/imagebakery@64bb2b9
> <https://github.com/xrmx/imagebakery/commit/64bb2b9a33b52713ff81c02cad30b0a3daf0ea42>.

ls would still return non zero on an empty directory though, no?


-- 
Riccardo Magliocchetti

**Comment by l1k** [comment]
<blockquote>lt would still return non zero on an empty directory though, no?</blockquote>

It seems that the return value is ignored if the command substitution happens between the square brackets. I tested with a little sample script and it worked fine.

**Comment by xrmx** [comment]
Il 12/06/2017 17:22, l1k ha scritto:
>     lt would still return non zero on an empty directory though, no?
>
> It seems that the return value is ignored if the command substitution happens
> between the square brackets. I tested with a little sample script and it worked
> fine.

thanks for checking, haven't done shell scripting in years :)

-- 
Riccardo Magliocchetti

**Comment by l1k** [comment]
Okay I've cherry-picked xrmx/imagebakery@ac4c7a202e11eac8d8e1638b7f153adbc72dac1c to enable qemu-arm-static support.

The reason why the apache2 processes are still hanging around even after invoking `/etc/init.d/apache2 stop` is that `pidof` is used to determine the PIDs, and `pidof` only looks at `argv[0]` when searching for the PIDs, which is "qemu-arm-static" instead of "apache2". The simplest solution it seems is to patch `/etc/init.d/apache2` to use `pidof -x`, which causes it to also look at `argv[1]`. I've pushed this solution with commit f121d3e44f6d058f0415181c46bd0d876ce75463. With that I can run `customize_image.sh` without errors on x86_64.

I think commit xrmx/imagebakery@37c5086240a64f6f4932e7ad1e9f86897a322149 may have been necessary as long as qemu-arm-static wasn't copied to the chroot. It doesn't seem to be needed to successfully customize an image.

As for commit xrmx/imagebakery@ee9f79c5bf556e8ec3dde0450162090f972f883b, this is only needed if `revpi-webstatus` was removed from `debs-to-download`, and if a user is willing to modify the image this much, it's probably acceptable that they'll also have to adjust `customize_image.sh` to not fiddle around with apache2.

I think I've addressed all commits in this pull now. Let me know if I've missed something. Thanks a lot for this contribution, I particularly like the ability to cross-build with qemu-arm-static.

**Comment by xrmx** [comment]
Il 13/06/2017 12:42, l1k ha scritto:
> Okay I've cherry-picked xrmx/imagebakery@ac4c7a2
> <https://github.com/xrmx/imagebakery/commit/ac4c7a202e11eac8d8e1638b7f153adbc72dac1c>
> to enable qemu-arm-static support.
>
> The reason why the apache2 processes are still hanging around even after
> invoking |/etc/init.d/apache2 stop| is that |pidof| is used to determine the
> PIDs, and |pidof| only looks at |argv[0]| when searching for the PIDs, which is
> "qemu-arm-static" instead of "apache2". The simplest solution it seems is to
> patch |/etc/init.d/apache2| to use |pidof -x|, which causes it to also look at
> |argv[1]|. I've pushed this solution with commit f121d3e
> <https://github.com/RevolutionPi/imagebakery/commit/f121d3e44f6d058f0415181c46bd0d876ce75463>.
> With that I can run |customize_image.sh| without errors on x86_64.

Thanks for digging into it!

> I think commit xrmx/imagebakery@37c5086
> <https://github.com/xrmx/imagebakery/commit/37c5086240a64f6f4932e7ad1e9f86897a322149>
> may have been necessary as long as qemu-arm-static wasn't copied to the chroot.
> It doesn't seem to be needed to successfully customize an image.

ok, will give it a try

> As for commit xrmx/imagebakery@ee9f79c
> <https://github.com/xrmx/imagebakery/commit/ee9f79c5bf556e8ec3dde0450162090f972f883b>,
> this is only needed if |revpi-webstatus| was removed from |debs-to-download|,
> and if a user is willing to modify the image this much, it's probably acceptable
> that they'll also have to adjust |customize_image.sh| to not fiddle around with
> apache2.

I think that to make imagebakery generic (which may not be your goal, i can see 
that :) the shell script must not assume anything about the installed packages. 
So i can live with a fork for having a different debs-to-download but i'd very 
much avoid having changes in the shell script. So if that patch could be merged 
it would make my life a lot easier :)

> I think I've addressed all commits in this pull now. Let me know if I've missed
> something. Thanks a lot for this contribution, I particularly like the ability
> to cross-build with qemu-arm-static.

Thanks for reviewing my PR!

-- 
Riccardo Magliocchetti

**Comment by xrmx** [comment]
I've rebased the PR keeping only the apache2 commit on top of master

**Comment by xrmx** [comment]
Thanks, much appreciated!

**Pull request merged**
