### PR TITLE
Specify node-red version for installation script

### PR DESCRIPTION
**Pull request by zhan-kunbus**
Signed-off-by: Zhi Han <z.han@kunbus.com>

### CODE REVIEW

**Comment by ferdrich-kunbus** [comment]
Spelling error in Commit header 93aedca: tailing -> trailing

Rest looks good.

**Comment by nbuchwitz** [comment]
@zhan-kunbus, Is this still a draft or ready to review?

**Comment by zhan-kunbus** [comment]
> Spelling error in Commit header [93aedca](https://github.com/RevolutionPi/imagebakery/commit/93aedca45856f003c23366dbcf25191d69617b24): tailing -> trailing
> 
> Rest looks good.

good catch, thx

**Comment by ferdrich-kunbus** [comment]
One more thing ... The part "automatically with vs code" is not relevant for any user, as there is no setting for VSCode, that is pushed alongside the changes in the source file. Reduce the commit message to "Trim trailing whitespaces", that is enough information.

**Review by nbuchwitz — APPROVED** [review]

**Pull request merged**
